# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraviz < Formula
  desc "Generate interactive architecture diagrams from Terraform state files or live AWS accounts"
  homepage "https://github.com/krishnaduttPanchagnula/TerraViz"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krishnaduttPanchagnula/TerraViz/releases/download/v0.1.2/terraviz_0.1.2_darwin_amd64.tar.gz"
      sha256 "3e5392c78c3275d3df4d803ddef8f77ebda36a2384d3543c7465f832361e90c3"

      define_method(:install) do
        bin.install "terraviz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krishnaduttPanchagnula/TerraViz/releases/download/v0.1.2/terraviz_0.1.2_darwin_arm64.tar.gz"
      sha256 "c3bdfe95ba33c094ad44c942364be32562d1806c199370732ac7e7aa74457069"

      define_method(:install) do
        bin.install "terraviz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krishnaduttPanchagnula/TerraViz/releases/download/v0.1.2/terraviz_0.1.2_linux_amd64.tar.gz"
      sha256 "aaa10684b7308a6f318821c6d50eb001f9a8b2eb63bfba3cab17cd9564cd6a22"
      define_method(:install) do
        bin.install "terraviz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krishnaduttPanchagnula/TerraViz/releases/download/v0.1.2/terraviz_0.1.2_linux_arm64.tar.gz"
      sha256 "85aa3a2eb9d38fc1d9ca109bae4a4fab7bfe29e89f9bb14dce055154fce256ac"
      define_method(:install) do
        bin.install "terraviz"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/terraviz --version")
  end
end
