# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraviz < Formula
  desc "Generate interactive architecture diagrams from Terraform state files or live AWS accounts"
  homepage "https://github.com/krishnaduttPanchagnula/TerraViz"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krishnaduttPanchagnula/TerraViz/releases/download/v0.1.4/terraviz_0.1.4_darwin_amd64.tar.gz"
      sha256 "827c7724cd77ac3239d3c87bd77f0232c71271fcb4116930e040900c2ad47487"

      define_method(:install) do
        bin.install "terraviz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/krishnaduttPanchagnula/TerraViz/releases/download/v0.1.4/terraviz_0.1.4_darwin_arm64.tar.gz"
      sha256 "03d46f966ec0d75f44d21e375430ec4b7945c56a0b3cc0867e2005cb23b2201f"

      define_method(:install) do
        bin.install "terraviz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/krishnaduttPanchagnula/TerraViz/releases/download/v0.1.4/terraviz_0.1.4_linux_amd64.tar.gz"
      sha256 "17e8147967c50a038e0300a32d4f445f41280dd6d23919e7dd2b69209ca3dc28"
      define_method(:install) do
        bin.install "terraviz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krishnaduttPanchagnula/TerraViz/releases/download/v0.1.4/terraviz_0.1.4_linux_arm64.tar.gz"
      sha256 "26afd99518b2e1ffd2cdda5e3a2075063cbf7db0228de11fa879499541a19923"
      define_method(:install) do
        bin.install "terraviz"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/terraviz --version")
  end
end
